#!/usr/bin/env bash
# install_linux.sh - Simple setup for the community-compute worker client on
# Linux: creates a venv, installs dependencies, saves your connection
# settings into a launcher script, and (optionally) registers a systemd
# --user service so the worker starts automatically and survives reboots.
#
# Usage:
#   ./install_linux.sh --server https://compute.example.org \
#       --engine-bin /path/to/chess_engine --api-key cek_xxxxxxxx [options]
#
# Any of --server/--engine-bin/--api-key not given on the command line are
# prompted for interactively (unless --non-interactive is passed, e.g. for
# scripted/CI installs, in which case missing required values are an error).
#
# See platform/docs/WORKER.md for how to get a server URL and API key.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKER_DIR="$(cd "$SCRIPT_DIR/../worker" && pwd)"

SERVER=""
ENGINE_BIN=""
API_KEY=""
THREADS=""
MAX_CPU_PERCENT=""
MAX_MEMORY_MB=""
INSTALL_SERVICE="ask"
NONINTERACTIVE=0

usage() {
    cat <<EOF
Usage: $0 [--server URL] [--engine-bin PATH] [--api-key KEY] [--threads N]
          [--max-cpu-percent N] [--max-memory-mb N]
          [--install-service | --no-service] [--non-interactive]
EOF
    exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
        --server) SERVER="$2"; shift 2 ;;
        --engine-bin) ENGINE_BIN="$2"; shift 2 ;;
        --api-key) API_KEY="$2"; shift 2 ;;
        --threads) THREADS="$2"; shift 2 ;;
        --max-cpu-percent) MAX_CPU_PERCENT="$2"; shift 2 ;;
        --max-memory-mb) MAX_MEMORY_MB="$2"; shift 2 ;;
        --install-service) INSTALL_SERVICE="yes"; shift ;;
        --no-service) INSTALL_SERVICE="no"; shift ;;
        --non-interactive) NONINTERACTIVE=1; shift ;;
        -h|--help) usage ;;
        *) echo "unknown argument: $1"; usage ;;
    esac
done

prompt() {
    # prompt VAR_NAME "question" "default"
    local __var="$1" __q="$2" __default="${3:-}" __ans
    if [ $NONINTERACTIVE -eq 1 ]; then
        if [ -z "${!__var}" ] && [ -z "$__default" ]; then
            echo "error: --$(echo "$__var" | tr '[:upper:]_' '[:lower:]-') is required in --non-interactive mode" >&2
            exit 1
        fi
        return
    fi
    if [ -n "${!__var}" ]; then
        return
    fi
    if [ -n "$__default" ]; then
        read -rp "$__q [$__default]: " __ans
        __ans="${__ans:-$__default}"
    else
        read -rp "$__q: " __ans
    fi
    printf -v "$__var" '%s' "$__ans"
}

echo "=== Morph Community Compute -- worker installer (Linux) ==="
echo "install directory: $WORKER_DIR"
echo

prompt SERVER "Platform server URL (e.g. https://compute.example.org)"
prompt ENGINE_BIN "Path to compiled chess engine UCI binary"
prompt API_KEY "Your API key (from the server's /accounts endpoints -- leave blank to use a shared registration secret instead)" "__none__"
[ "$API_KEY" = "__none__" ] && API_KEY=""
prompt THREADS "Number of concurrent self-play threads" "1"

if [ -z "$SERVER" ]; then echo "error: server URL is required" >&2; exit 1; fi
if [ ! -x "$ENGINE_BIN" ] && [ ! -f "$ENGINE_BIN" ]; then
    echo "warning: $ENGINE_BIN does not look like an existing file -- continuing anyway"
fi

command -v python3 >/dev/null 2>&1 || { echo "error: python3 is required but not found"; exit 1; }
PYVER=$(python3 -c 'import sys; print(sys.version_info[:2])')
echo "found python3 ($PYVER)"

echo "--- creating virtual environment at $WORKER_DIR/venv ---"
# A plain, isolated venv (no --system-site-packages) -- keeps the worker's
# dependencies pinned and independent of whatever else is installed
# system-wide, and avoids symlink-related surprises that
# --system-site-packages can cause on some network/synced filesystems.
if [ -d "$WORKER_DIR/venv" ]; then
    echo "venv already exists, reusing it (delete $WORKER_DIR/venv to force a clean rebuild)"
else
    python3 -m venv "$WORKER_DIR/venv"
fi
"$WORKER_DIR/venv/bin/pip" install --quiet --upgrade pip
"$WORKER_DIR/venv/bin/pip" install --quiet -r "$WORKER_DIR/requirements.txt"
echo "dependencies installed"

RUN_SCRIPT="$WORKER_DIR/run.sh"
{
    echo "#!/usr/bin/env bash"
    echo "# Generated by install_linux.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Edit freely, or re-run"
    echo "# install_linux.sh to regenerate."
    echo "set -e"
    echo "cd \"$WORKER_DIR\""
    printf 'exec "%s/venv/bin/python3" run_platform_worker.py \\\n' "$WORKER_DIR"
    printf '    --server %q \\\n' "$SERVER"
    printf '    --engine-bin %q \\\n' "$ENGINE_BIN"
    [ -n "$API_KEY" ] && printf '    --api-key %q \\\n' "$API_KEY"
    printf '    --threads %q \\\n' "${THREADS:-1}"
    [ -n "$MAX_CPU_PERCENT" ] && printf '    --max-cpu-percent %q \\\n' "$MAX_CPU_PERCENT"
    [ -n "$MAX_MEMORY_MB" ] && printf '    --max-memory-mb %q \\\n' "$MAX_MEMORY_MB"
    echo '    "$@"'
} > "$RUN_SCRIPT"
chmod +x "$RUN_SCRIPT"
echo "wrote launcher: $RUN_SCRIPT"

if [ "$INSTALL_SERVICE" = "ask" ] && [ $NONINTERACTIVE -eq 0 ]; then
    read -rp "Install as a systemd --user service (auto-starts on login/boot)? [y/N]: " yn
    [[ "$yn" =~ ^[Yy] ]] && INSTALL_SERVICE=yes || INSTALL_SERVICE=no
fi

if [ "$INSTALL_SERVICE" = "yes" ]; then
    if ! command -v systemctl >/dev/null 2>&1; then
        echo "systemctl not found -- skipping service install. Run $RUN_SCRIPT manually instead."
    else
        UNIT_DIR="$HOME/.config/systemd/user"
        mkdir -p "$UNIT_DIR"
        UNIT_FILE="$UNIT_DIR/chess-compute-worker.service"
        cat > "$UNIT_FILE" <<EOF
[Unit]
Description=Morph Community Compute worker
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$RUN_SCRIPT
Restart=on-failure
RestartSec=15

[Install]
WantedBy=default.target
EOF
        systemctl --user daemon-reload
        systemctl --user enable chess-compute-worker.service
        echo "installed and enabled systemd --user service: chess-compute-worker.service"
        echo "start now with: systemctl --user start chess-compute-worker.service"
        echo "view logs with: journalctl --user -u chess-compute-worker.service -f"
        echo "(enable lingering with 'loginctl enable-linger \$USER' so it also runs while logged out)"
    fi
else
    echo "skipped service install. Start the worker manually with: $RUN_SCRIPT"
fi

echo
echo "=== done ==="
echo "test it now with: $RUN_SCRIPT --once"
